POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "fuck you",
    "number": "12345"
}

###
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "name hai na bc", 
    "number": "qwefwfwfw"
}